[
    {"selenium_name": "iehta", "short_version": "9", "long_name": "Internet Explorer", "long_version": "9.0.8080.16413.", "preferred_version": "9", "os": "Windows 2008"},
    {"selenium_name": "iexplore", "short_version": "9", "long_name": "Internet Explorer", "long_version": "9.0.8080.16413.", "preferred_version": "9", "os": "Windows 2008"},
    {"selenium_name": "iexploreproxy", "short_version": "9", "long_name": "Internet Explorer [Proxy mode]", "long_version": "9.0.8080.16413.", "preferred_version": "9", "os": "Windows 2008"},
    {"selenium_name": "iehta", "short_version": "8", "long_name": "Internet Explorer", "long_version": "8.0.6001.18702.", "preferred_version": "8", "os": "Windows 2003"},
    {"selenium_name": "iehta", "short_version": "7", "long_name": "Internet Explorer", "long_version": "7.0.5730.13.", "preferred_version": "8", "os": "Windows 2003"},
    {"selenium_name": "iehta", "short_version": "6", "long_name": "Internet Explorer", "long_version": "6.0.3790.1830.", "preferred_version": "8", "os": "Windows 2003"},
    {"selenium_name": "iexplore", "short_version": "8", "long_name": "Internet Explorer", "long_version": "8.0.6001.18702.", "preferred_version": "8", "os": "Windows 2003"},
    {"selenium_name": "iexplore", "short_version": "7", "long_name": "Internet Explorer", "long_version": "7.0.5730.13.", "preferred_version": "8", "os": "Windows 2003"},
    {"selenium_name": "iexplore", "short_version": "6", "long_name": "Internet Explorer", "long_version": "6.0.3790.1830.", "preferred_version": "8", "os": "Windows 2003"},
    {"selenium_name": "iexploreproxy", "short_version": "8", "long_name": "Internet Explorer [Proxy mode]", "long_version": "8.0.6001.18702.", "preferred_version": "8", "os": "Windows 2003"},
    {"selenium_name": "iexploreproxy", "short_version": "7", "long_name": "Internet Explorer [Proxy mode]", "long_version": "7.0.5730.13.", "preferred_version": "8", "os": "Windows 2003"},
    {"selenium_name": "iexploreproxy", "short_version": "6", "long_name": "Internet Explorer [Proxy mode]", "long_version": "6.0.3790.1830.", "preferred_version": "8", "os": "Windows 2003"},
    {"selenium_name": "firefox", "short_version": "4", "long_name": "Firefox", "long_version": "4.0.", "preferred_version": "4", "os": "Windows 2008"},
    {"selenium_name": "chrome", "short_version": "4", "long_name": "Firefox", "long_version": "4.0.", "preferred_version": "4", "os": "Windows 2008"},
    {"selenium_name": "firefoxproxy", "short_version": "4", "long_name": "Firefox [Proxy mode]", "long_version": "4.0.", "preferred_version": "4", "os": "Windows 2008"},
    {"selenium_name": "firefox", "short_version": "3.5", "long_name": "Firefox", "long_version": "3.5.16.", "preferred_version": "3.6", "os": "Windows 2003"},
    {"selenium_name": "firefox", "short_version": "3.6", "long_name": "Firefox", "long_version": "3.6.13.", "preferred_version": "3.6", "os": "Windows 2003"},
    {"selenium_name": "firefox", "short_version": "3.0", "long_name": "Firefox", "long_version": "3.0.19.", "preferred_version": "3.6", "os": "Windows 2003"},
    {"selenium_name": "firefox", "short_version": "2.0", "long_name": "Firefox", "long_version": "2.0.0.20.", "preferred_version": "3.6", "os": "Windows 2003"},
    {"selenium_name": "firefox", "short_version": "3.6", "long_name": "Firefox", "long_version": "3.6.16.", "preferred_version": "3.6", "os": "Windows 2003"},
    {"selenium_name": "chrome", "short_version": "3.5", "long_name": "Firefox", "long_version": "3.5.16.", "preferred_version": "3.6", "os": "Windows 2003"},
    {"selenium_name": "chrome", "short_version": "3.6", "long_name": "Firefox", "long_version": "3.6.13.", "preferred_version": "3.6", "os": "Windows 2003"},
    {"selenium_name": "chrome", "short_version": "3.0", "long_name": "Firefox", "long_version": "3.0.19.", "preferred_version": "3.6", "os": "Windows 2003"},
    {"selenium_name": "chrome", "short_version": "2.0", "long_name": "Firefox", "long_version": "2.0.0.20.", "preferred_version": "3.6", "os": "Windows 2003"},
    {"selenium_name": "chrome", "short_version": "3.6", "long_name": "Firefox", "long_version": "3.6.16.", "preferred_version": "3.6", "os": "Windows 2003"},
    {"selenium_name": "firefoxproxy", "short_version": "3.5", "long_name": "Firefox [Proxy mode]", "long_version": "3.5.16.", "preferred_version": "3.6", "os": "Windows 2003"},
    {"selenium_name": "firefoxproxy", "short_version": "3.6", "long_name": "Firefox [Proxy mode]", "long_version": "3.6.13.", "preferred_version": "3.6", "os": "Windows 2003"},
    {"selenium_name": "firefoxproxy", "short_version": "3.0", "long_name": "Firefox [Proxy mode]", "long_version": "3.0.19.", "preferred_version": "3.6", "os": "Windows 2003"},
    {"selenium_name": "firefoxproxy", "short_version": "2.0", "long_name": "Firefox [Proxy mode]", "long_version": "2.0.0.20.", "preferred_version": "3.6", "os": "Windows 2003"},
    {"selenium_name": "firefoxproxy", "short_version": "3.6", "long_name": "Firefox [Proxy mode]", "long_version": "3.6.16.", "preferred_version": "3.6", "os": "Windows 2003"},
    {"selenium_name": "safariproxy", "short_version": "5", "long_name": "Safari [Proxy mode]", "long_version": "5.0.5.", "preferred_version": "4", "os": "Windows 2003"},
    {"selenium_name": "safariproxy", "short_version": "4", "long_name": "Safari [Proxy mode]", "long_version": "4.0.5.", "preferred_version": "4", "os": "Windows 2003"},
    {"selenium_name": "safariproxy", "short_version": "5", "long_name": "Safari [Proxy mode]", "long_version": "5.0.3.7533.19.4.", "preferred_version": "4", "os": "Windows 2003"},
    {"selenium_name": "safariproxy", "short_version": "3", "long_name": "Safari [Proxy mode]", "long_version": "3.2.3.", "preferred_version": "4", "os": "Windows 2003"},
    {"selenium_name": "safari", "short_version": "4", "long_name": "Safari", "long_version": "4.0.5.", "preferred_version": "4", "os": "Windows 2003"},
    {"selenium_name": "safari", "short_version": "3", "long_name": "Safari", "long_version": "3.2.3.", "preferred_version": "4", "os": "Windows 2003"},
    {"selenium_name": "googlechrome", "short_version": "", "long_name": "Google Chrome", "long_version": "8.0.552.237.", "preferred_version": "", "os": "Windows 2003"},
    {"selenium_name": "opera", "short_version": "11", "long_name": "Opera", "long_version": "11.00.1156.", "preferred_version": "11", "os": "Windows 2003"},
    {"selenium_name": "opera", "short_version": "10", "long_name": "Opera", "long_version": "10.63.", "preferred_version": "11", "os": "Windows 2003"},
    {"selenium_name": "opera", "short_version": "9", "long_name": "Opera", "long_version": "9.64.", "preferred_version": "11", "os": "Windows 2003"},
    {"selenium_name": "firefox", "short_version": "3.0", "long_name": "Firefox", "long_version": "3.0.19.", "preferred_version": "3.6", "os": "Linux"},
    {"selenium_name": "firefox", "short_version": "3.6", "long_name": "Firefox", "long_version": "3.6.10.", "preferred_version": "3.6", "os": "Linux"},
    {"selenium_name": "firefox", "short_version": "3.6", "long_name": "Firefox", "long_version": "3.6.16.", "preferred_version": "3.6", "os": "Linux"},
    {"selenium_name": "chrome", "short_version": "3.0", "long_name": "Firefox", "long_version": "3.0.19.", "preferred_version": "3.6", "os": "Linux"},
    {"selenium_name": "chrome", "short_version": "3.6", "long_name": "Firefox", "long_version": "3.6.10.", "preferred_version": "3.6", "os": "Linux"},
    {"selenium_name": "chrome", "short_version": "3.6", "long_name": "Firefox", "long_version": "3.6.16.", "preferred_version": "3.6", "os": "Linux"},
    {"selenium_name": "firefoxproxy", "short_version": "3.0", "long_name": "Firefox [Proxy mode]", "long_version": "3.0.19.", "preferred_version": "3.6", "os": "Linux"},
    {"selenium_name": "firefoxproxy", "short_version": "3.6", "long_name": "Firefox [Proxy mode]", "long_version": "3.6.10.", "preferred_version": "3.6", "os": "Linux"},
    {"selenium_name": "firefoxproxy", "short_version": "3.6", "long_name": "Firefox [Proxy mode]", "long_version": "3.6.16.", "preferred_version": "3.6", "os": "Linux"}
]