name: ci-sauce CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    strategy:
      matrix:
        platform: [ ubuntu-latest, macos-latest, windows-latest ]
      fail-fast: false

    runs-on: ${{ matrix.platform }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 11
          cache: 'maven'

      - name: Build
        shell: bash
        run: ./mvnw install -Dgpg.skip=true -B -V

      # As per https://github.com/codecov/codecov-action/issues/295 the repo needs to be
      # registered to be able to use https://github.com/codecov/codecov-action
      - name: Upload coverage to Codecov
        if: matrix.platform == 'ubuntu-latest'
        run: |
          curl -Os https://uploader.codecov.io/latest/linux/codecov
          chmod +x codecov
          ./codecov
